### ISSUE TITLE
USB support 

### ISSUE THREAD

**Issue by HatalDev** [vicary/react-native-citizen-escposprinter#6]
Hi,
When trying to search for a printer and choose the usb port as the communication port, an error appear in the library saying the device is not supported (js error), does this package support usb connection? If so can you attached an example? If not there is any attention to do so?

 Thanks in advance for this great package

**Comment by vicary** [comment]
It's not implemented yet.

Unlike IP addresses, MAC addresses or Bluetooth hostnames, there is no trivial way of acquiring serializable data format to indetify an USBDevice instance back and forth between javascript and the native layers.

I am open for discussions and accept pull requests. e.g. You may share a repo link, if you have seen other React Native plugins do this.

**Comment by HatalDev** [comment]
Thank you for the response.
This package https://github.com/tr3v3r/react-native-esc-pos-printer doing the same just for epson printers and it support usb as well, maybe it can help

**Comment by vicary** [comment]
The EPSON printer is connecting via a connection string for all devices, for USB connections it starts with something like `"USB:/"`. These connection strings are simply returned by their discovery service, the React Native plugin has no extra work to do.

## What?

What we can do right now is supporting USB via auto-detection. Which means it happily connects to any compatible printer, and users cannot specify a serial number.

## Why?

The Citizen SDK for iOS is trivial to enable support, because the second parameter is an optional string,
```swift
// Auto-detection
printer!.connect(CMP_PORT_USB)
// With serial number
printer!.connect(CMP_PORT_USB, withAddress: usbSerialNo)
```

But we don't know how to restrict USB connections with a specified serial number in Android

```kotlin
// Auto-detection
val usbDevice: UsbDevice? = null
printer.connect(ESCPOSConst.CMP_PORT_USB, usbDevice)

// With serial number
// We don't know how.
```

## How?

We don't have USB Citizen printers for testing. To move forward, we may have to rely on someone who has them.

1. We can open a new PR with USB auto-detection enabled.
2. We need someone who owns a USB printer to perform tests on that PR.

### Test Prints

We did test prints on all 4 platforms, using the example app in this repo.
1. iOS "old" arch
2. iOS newarch
3. Android "old" arch
4. Android newarch

It would be great if this new feature is able to provide the same level of confidence for future users.

@HatalDev What do you think?

**Comment by HatalDev** [comment]
@vicary it's seems like a great option to try, I've citizen printers that I can help you with testing, if you could open a new PR I could try to run it with my android tablet and citizen printer via usb, let's give it a try.
